[greeter]
background=/usr/share/backgrounds/drakonis-linux/Drakonis-Linux.png
logo=/usr/share/pixmaps/drakonis-linux/drakonis-mark.png
theme-name=DRAKONIS-Night
icon-theme-name=hicolor
font-name=Sans 11
clock-format=%a %d %b  %H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~language;~power
