[greeter]
background=/usr/share/backgrounds/drakonis-linux/Drakonis-Login.png
logo=/usr/share/pixmaps/drakonis-linux/drakonis-mark.png
theme-name=DRAKONIS-Night
icon-theme-name=hicolor
font-name=Sans 11
show-password-label=true
show-manual-login=true
hide-user-image=false
indicators=~host;~spacer;~clock;~spacer;~session;~language;~power
clock-format=%a %d %b  %H:%M
