#!/bin/sh
set -e
lb config \
  --mode debian \
  --distribution stable \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free-firmware" \
  --debian-installer false \
  --initsystem systemd \
  --bootappend-live "boot=live components username=analyst hostname=drakonis-linux quiet splash" \
  --iso-application "Drakonis Linux" \
  --iso-publisher "Drakonis Linux Project" \
  --iso-volume "DRAKONIS_STABLE_X86_64" \
  --memtest none \
  --firmware-chroot false \
  --apt-recommends true \
  --apt-indices false \
  --security false
