#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
fail=0
for path in README.md VERSION config/auto/config config/package-lists/mll-core.list.chroot includes.chroot/etc/motd includes.chroot/usr/local/bin/mll-help includes.chroot/usr/local/bin/mll-release includes.chroot/usr/local/bin/mll-network-isolation includes.chroot/usr/local/bin/mll-install-profile includes.chroot/usr/local/bin/drakonis-security-center includes.chroot/usr/local/bin/drakonis-network-tools includes.chroot/usr/local/bin/drakonis-help-center includes.chroot/usr/local/bin/drakonis-themes-manager includes.chroot/usr/local/bin/drakonis-first-run includes.chroot/usr/local/bin/drakonis-power-session includes.chroot/usr/local/bin/drakonis-control-center includes.chroot/usr/local/bin/drakonis-vault includes.chroot/usr/local/bin/drakonis-software-center includes.chroot/usr/local/sbin/drakonis-initial-password includes.chroot/etc/systemd/system/drakonis-initial-password.service includes.chroot/etc/systemd/system/multi-user.target.wants/drakonis-initial-password.service includes.chroot/usr/local/libexec/drakonis-center.py includes.chroot/usr/local/libexec/drakonis-vault.py includes.chroot/usr/local/libexec/drakonis-vault-ui.py hooks/normal/0100-mll-hardening.chroot hooks/normal/0150-mll-tool-profiles.chroot docs/ARCHITECTURE.md docs/DESIGN-IMPLEMENTATION.md docs/EVIDENCE-VAULT.md docs/RELEASE-CHECKLIST.md docs/BUILD-TROUBLESHOOTING.md docs/TOOL-PROFILES.md profiles/blackarch/README.md scripts/build-iso.sh scripts/build-ova.sh scripts/install-blackarch-tools.sh scripts/install-profile.sh config/package-profiles/network.list config/package-profiles/web.list config/package-profiles/passwords.list config/package-profiles/wireless.list config/package-profiles/forensics.list config/package-profiles/reverse.list config/package-profiles/exploitation.list config/package-profiles/redteam.list includes.chroot/usr/local/share/mll/package-profiles/redteam.list; do
  if [ ! -f "$ROOT/$path" ]; then echo "MISSING $path"; fail=1; fi
done
for path in config/auto/config includes.chroot/usr/local/bin/mll-help includes.chroot/usr/local/bin/mll-release includes.chroot/usr/local/bin/mll-network-isolation includes.chroot/usr/local/bin/mll-install-profile includes.chroot/usr/local/bin/drakonis-security-center includes.chroot/usr/local/bin/drakonis-network-tools includes.chroot/usr/local/bin/drakonis-help-center includes.chroot/usr/local/bin/drakonis-themes-manager includes.chroot/usr/local/bin/drakonis-first-run includes.chroot/usr/local/bin/drakonis-power-session includes.chroot/usr/local/bin/drakonis-control-center includes.chroot/usr/local/bin/drakonis-vault includes.chroot/usr/local/bin/drakonis-vault-ui includes.chroot/usr/local/bin/drakonis-software-center includes.chroot/usr/local/sbin/drakonis-initial-password hooks/normal/0100-mll-hardening.chroot hooks/normal/0150-mll-tool-profiles.chroot scripts/build-iso.sh scripts/build-ova.sh scripts/install-blackarch-tools.sh scripts/install-profile.sh; do
  sh -n "$ROOT/$path" || fail=1
done
python3 -m py_compile "$ROOT/includes.chroot/usr/local/libexec/drakonis-center.py" "$ROOT/includes.chroot/usr/local/libexec/drakonis-vault.py" "$ROOT/includes.chroot/usr/local/libexec/drakonis-vault-ui.py" 2>/dev/null || fail=1
if grep -RniE 'password[[:space:]]*[=:]|secret[[:space:]]*[=:]|api[_-]?key[[:space:]]*[=:]|private[_-]?key[[:space:]]*[=:]|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY' "$ROOT/includes.chroot" "$ROOT/hooks" 2>/dev/null; then echo 'Potential secret-like content found'; fail=1; fi
if grep -RniE 'credential dump|steal' "$ROOT/includes.chroot" "$ROOT/hooks" 2>/dev/null; then echo 'Potentially unsafe payload wording found'; fail=1; fi
[ "$fail" -eq 0 ] && echo 'Project checks passed.'
exit "$fail"
